FROM python:3.7-alpine

RUN adduser -D projectblog

WORKDIR /home/projectblog

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn

COPY app app
COPY migrations migrations
COPY projectblog.py config.py ./

ENV FLASK_APP=projectblog.py

RUN chown -R projectblog:projectblog ./
USER projectblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
